### ISSUE TITLE
crash on Intel GPUs and solution..

### ISSUE THREAD

**Issue by oscarbg** [msiglreith/rostkatze#2]
Hi,
just tested rostkatze (had to create json you should share one premade) on AMD GPU with gltf-PBR sample and works ok..
but on Intel GPU crashes..
so I fixed crash by commenting:
```
/*if (pipeline->static_depth_bounds) {
                const auto [min, max] = *pipeline->static_depth_bounds;
                (*command_buffer)->OMSetDepthBounds(min, max);
            }*/
```
with that sample works correctly..
of course correct way would be to detect at runtime if GPU supports depth bounds test and if no disable this code i.e.:
if (pipeline->static_depth_bounds&&supports_dbt)

thanks..

**Comment by msiglreith** [comment]
Thanks for testing.
Pushed a small fix and disabled by depth bound feature by default for now until I add proper feature checks.
Could you check if it still crashes?

Oh, didn't notice that I didn't include the manifest files, will add some dummy ones later.

**Comment by oscarbg** [comment]
ok will test soon and report..
