### ISSUE TITLE
Can add UWP sample..

### ISSUE THREAD

**Issue by oscarbg** [msiglreith/rostkatze#7]
Seems you added UWP support.. great!
for the lazy ones can you add some minimal sample using it?
modifying VulkanOnD3D12 cube UWP sample to use your extension (https://github.com/Chabloom/VulkanOnD3D12/commit/b7de013314c1e91ef1f85168c893129adbc450ba)
will do the trick?
thanks..

**Comment by msiglreith** [comment]
Thanks, will look into adding UWP support to SaschaWillems Samples in a fork. This would be the nicest solution IMO

**Comment by msiglreith** [comment]
Got the triangle example running with UWP. Need to cleanup the changes and see if I can do content shipping a bit more nicely. Turns out UWP is a bit more annoying to use due to it's sandboxed nature (bundle shaders/data and can't use env vars for the vulkan loader..)

**Comment by msiglreith** [comment]
Add a fork with build instructions for the triangle example of the SaschaWillems samples.
https://github.com/msiglreith/rostkatze/wiki/UWP-example
